### ISSUE TITLE
APOD images are blocked by CORS policy

### ISSUE THREAD

**Issue by ezekielaquino** [nasa/api-docs#131]
Browser: all modern browsers

Steps to reproduce:
Load an image from the APOD api via js `new Image`. Even with crossOrigins set to 'anonymous' or blank, CORS blocks it. the only way to load it via js is to use a browser extension to force CORS. This would be beneficial to render images onto e.g. a canvas

**Comment by JustinGOSSES** [comment]
Unable to replicate. 

For example, see this ObservableHQ notebook where someone else (not this person) is using the APOD API to get images back. https://observablehq.com/@nclarkcoder/request-playground

Suspect the issue is how you're setting up your HTML/CS/JS page and maybe where it is being deployed? CORS is annoying at times. Best of luck.
