### ISSUE TITLE
 The api is not returning to sea temperatures!

### ISSUE THREAD

**Issue by thiagodevvv** [nasa/api-docs#144]
Hi, I'm trying to use the Mars climate api, but it's not getting the right temperatures back!
In:https://mars.nasa.gov/insight/weather/https://mars.nasa.gov/insight/weather/
and api too
https://api.nasa.gov/insight_weather/?api_key=hyAFBcLDCctNdFVXIqi8bNavGFJDY0HhTbcE7IRP&feedtype=json&ver=1.0

**Comment by JustinGOSSES** [comment]
My limited understanding is data on windspeed is not being sent from Rover to Earth right now and this has been an issue since ~ November 2021.  If you go to https://mars.nasa.gov/insight/weather/ and scroll down to the "seasonal weather report" you'll see the gaps.

It isn't an api.nasa.gov issue but rather that that data isn't available.

**Comment by JustinGOSSES** [comment]
As noted in the insight section of the APIs, the appropriate feedback for the API is https://mars.nasa.gov/feedback/  api.nasa.gov is just a pass through service. 

I'll add a more explicit note about missing data for some sensors for some dates on the API description.
