### ISSUE TITLE
Earth API Down

### ISSUE THREAD

**Issue by natholder** [nasa/api-docs#164]
Using the Earth API to retrieve Landsat 8 images, getting 500 internal server errors, even with the example request.

https://api.nasa.gov/planetary/earth/imagery?lon=-95.33&lat=29.78&date=2018-01-01&dim=0.15&api_key=DEMO_KEY

**Comment by natholder** [comment]
Actively being fixed, closing issue

**Comment by PerryMapping** [comment]
It is probably due to Google Earth Engine migrating to Landsat Collection 2.  The example request works if you request the asset rather than the imagery. If you try to make a request from before 12/31/21, you'll see that the key alludes to collection 1: `"id":"LANDSAT/LC08/C01/T1_SR/` 

[Info from Google documentation](https://developers.google.com/earth-engine/datasets/catalog/landsat)
