### ISSUE TITLE
Enable CORS on Landsat API

### ISSUE THREAD

**Issue by chrisalexander** [nasa/api-docs#39]
As per #37, the Landsat API does not currently send an Access-Control-Allow-Origin header with responses.

**Comment by danhammer** [comment]
I've added CORS support for the meta queries like this:
```bash
https://api.nasa.gov/planetary/earth/imagery?date=2015-05-01&cloud_score=True&api_key=DEMO_KEY
```
I am going to leave this issue open, however, because I am still working on enabling CORS for the image itself -- which is served out through Earth Engine.  @chrisalexander, is this issue regarding the metadata associated with the Landsat images, or the actual image, or both?  If the latter two, I will close this issue and open a new one.  Otherwise I can close it when I update the documentation page.

**Comment by chrisalexander** [comment]
Hi @danhammer - thanks, that is working nicely.

There is no need to do the image URLs - they can be loaded using an img tag quite easily.

Thanks very much!
