### ISSUE TITLE
APOD api suggestion: add ability to return images based on a number or date range

### ISSUE THREAD

**Issue by AdamMurray** [nasa/api-docs#44]
I'm thinking of something like:

https://api.nasa.gov/planetary/apod?count=10&api_key=DEMO_KEY

to return the 10 most recent images. Or:

https://api.nasa.gov/planetary/apod?startDate=2015-04-27&endDate=2015-01-01&api_key=DEMO_KEY

to return images between the start and end dates.

**Comment by benjaminboruff** [comment]
+1
I like this idea. The start and end dates would probably suffice. I was going to write a frontend app to craft the appropriate number of requests based on user input, but that would mean a lot of requests - those are expensive in terms of time to get the data, then process and request the images, etc.... So instead of 10 requests/responses, there would only be one request/response. (The JSON response would be a string representing an array of 10 objects, or however many requested. ) Would that ease the load on the API endpoint server's network load? Or increase the load on the DB? It may be a wash.

**Comment by gdomingu** [comment]
+1

**Comment by MichalPaszkiewicz** [comment]
+1

**Comment by brianthomas** [comment]
+1

**Comment by joshuatbrown** [comment]
Yes please! :+1:

**Comment by suemareverton** [comment]
+1

**Comment by martinsuchan** [comment]
I like this idea. It might be sufficient to add endpoint for returning all images published in the target month, somethng like:
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY&month=2015-04

**Comment by jnbetancourt** [comment]
The latest release of the apod api includes the ability to specify a date range. The details are in the README at: https://github.com/nasa/apod-api
