### ISSUE TITLE
Video format sometimes in the APOD API

### ISSUE THREAD

**Issue by Dinchy87** [nasa/api-docs#66]
hi guys, im using this API APOD for my Windows universal app and so far i like it a lot but is have a small issue with it or two issues.

The first one is that i need only Pictures in my app but he APOD API gives sometimes an Video back, my question is, can it be done that with this Video in the API there is also an Picture fromt his Video some. Or some way to opt out the Video. Currently i parse the JSON and if the media Format is Video i dont use this, but there is a Problem, new users that download my app on the day when the APOD API Shows a Video i dont have anything to Show to them :/

And the second issue, right now i have called the API and it says "error": "No APOD imagery for the given date.", but i have not specified any date, it should Display the todays Image data?! or not? I think maybe you upload the newset Picture and in this timeframe there is no data? can we fix this somehow? ist easy for me to skip this span until next time the app checks for new data but does it have to be like this? can the old Image dissapear from the API only if a new one is posted?

Best regards.

**Comment by The-Penultimate-Defenestrator** [comment]
as far as the first issue, solve it on your end. If there's a video today, call the API again with yesterday as the date. Just see whether what you get back is an image or video, and if it's a video keep going back in time until the API returns an image

**Comment by brianthomas** [comment]
For the second issue, it may be related to timezone mismatch problem in https://github.com/nasa/api-docs/issues/67. I've pushed a fix where it will check for the prior day if the current (today's) day appears unavailable (this is only in the case you *didnt* specify the date param). Since this appears to be addressing the same problem, and I agree with the prior comment about the first issue, I will close this one.
