### ISSUE TITLE
No APOD imagery for the given date

### ISSUE THREAD

**Issue by sabsowitz** [nasa/api-docs#67]
I'm not sure if this had been submitted as an issue. I use APOD on my website using my api key. I've noticed that every evening (eastern time), APOD stops displaying on my website. It works for most of the day, and then stops working... very frequently. Investigating, I made an api call with my api key, and returned the following json:

{
  "error": "No APOD imagery for the given date.",
  "message": "Your request could not be processed.",
  "service_version": "v1"
}

I then tried making the api call with the Demo_Key to make sure the issue wasn't my api key. Am I the only person who is having this issue?

**Comment by brianthomas** [comment]
I think this is a result of the port to Heroku. The service is issuing GMT time vs APOD underlying site which is on the east coast of US (I think). The ~4-5 hr time gap results in a period of time of the same size where the service is trying to grab the *next* day (into the future) rather than current day. I'll try to fix it.

**Comment by brianthomas** [comment]
I've pushed a fix to the service, please see if this fixes the issue for you

**Comment by sabsowitz** [comment]
Fixed.
