### ISSUE TITLE
Some dates always return 505 code, Internal Service Error

### ISSUE THREAD

**Issue by benjaminboruff** [nasa/api-docs#69]
If you try to access some dates, such as 1995-06-16 (the APOD birthdate!), or 1996-07-28, or many, many other seemingly random dates, they ALWAYS return a code 505 "Internal Service Error."

Out of a sample of 1000 consecutive, valid dates, I found about 25% always return the 505 code. I have tried using a browser, curl, Node.js, PHP, etc. All the same. If this occurs for only specific dates, does that mean some kind of database corruption?

**Comment by martinsuchan** [comment]
This is a duplicate to this issue:
https://github.com/nasa/NASA-APIs/issues/14

Here's my summary when I was checking for missing dates:

I've created fetch script to check all days since the start of APOD on 20th June 1996 and found 530 missing days on server returning INTERNAL SERVER ERROR, that's about 7% of all APOD images published since the start.

The full list of days that return error is available here:
http://pastebin.com/fHDRN5Kw

**Comment by jnbetancourt** [comment]
Updates to the APOD API have been made. I checked the 1995-06-16 and 1996-07-28 and they're working now. Feel free to re-open this issue if you find other dates that are failing.
